### ISSUE TITLE
Contribute new ideas for usage / feature or anything you find interesting about the library [Hacktoberfest friendly]

### ISSUE THREAD

**Issue by Pradyuman7** [Pradyuman7/LookAtMe#7]
Share your ideas in the [Ideas.md](https://github.com/Pradyuman7/LookAtMe/blob/master/Ideas.md) file

Fork this repository, add your ideas and open a pull request 👍

**Comment by ConnectNitish** [comment]
I would like to add some ideas into the same.

**Comment by Pradyuman7** [comment]
@ConnectNitish feel free to fork the repository and add your ideas. Please take a look at the rules (in the same file) before adding any ideas. Rules are there to make sure your contribution counts.
😄 👍
